### ISSUE TITLE
[ID] Tool to generate FW with different IDs.

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/EC-LC-NEMA#31]
At this moment, the ID is hardcoded in the FW but we need to create hundreds of FWs, one different per device. It is necessary to have an script that allows the change of the ID without generates any other FW.

Expected behaviour:

- We have one .hex
- ./generate_6lp_hex.sh path/to/original_hex start_id end_id
- start_id and end_id are Hexadecimal numbers
- Example: 
./generate_6lp_hex.sh path/to/original_hex 777010 77701F 
Creates 16 executables: 777010.hex, 777011.hex.... 77701E and 77701F

**Comment by ralcaide** [comment]
@fpgamcu , could you provide an estimation about this requirement? Could you do that with high priority, please?

**Comment by fpgamcu** [comment]
I will be able to do it today.
Need to change ID location from #define to const uint32_t and place it to fixed memory address.
After this it will be possible to edit hex with bash commands and change id in hex

**Comment by fpgamcu** [comment]
Script added into Source/Debug folder
Please execute it from those folder, like
``` cd Source/Debug```
```./gen.sh```
First build project in true studio and then you will be able to execute script
In script there is STARTID and ENDID variables at the top of the script
Please modify them in order to use different IDs
For example for 777010 to 77701F
```let "STARTID = 0x777010"```
```let "ENDID = 0x77701F"```

**Comment by ralcaide** [comment]
Tested with tag EC_NEMA_LC_6LP_D_V19.20.02 OK
